# Unity test build
# Usage: make -f tests/Makefile.unity [test|clean]

CC      := gcc
CFLAGS  := -std=c99 -pedantic -Wall -Wextra -Werror -I. -Isrc -Itests

# All SyntropicOS source files
SYN_SRCS := \
	src/syntropic/drivers/syn_gpio.c src/syntropic/drivers/syn_uart.c \
	src/syntropic/drivers/syn_adc.c src/syntropic/drivers/syn_exti.c \
	src/syntropic/drivers/syn_can.c src/syntropic/drivers/syn_soft_i2c.c \
	src/syntropic/drivers/syn_soft_spi.c src/syntropic/drivers/syn_sd.c \
	src/syntropic/drivers/syn_rtc.c src/syntropic/drivers/syn_soft_onewire.c \
	src/syntropic/drivers/syn_dac.c \
	src/syntropic/util/syn_ringbuf.c src/syntropic/util/syn_fsm.c \
	src/syntropic/util/syn_crc.c src/syntropic/util/syn_fmt.c \
	src/syntropic/util/syn_ramp.c src/syntropic/util/syn_scurve.c \
	src/syntropic/util/syn_cbor_write.c src/syntropic/util/syn_cbor_read.c \
	src/syntropic/util/syn_pubsub.c \
	src/syntropic/sched/syn_sched.c src/syntropic/sched/syn_timer.c \
	src/syntropic/sched/syn_watchdog.c src/syntropic/sched/syn_sequencer.c \
	src/syntropic/sched/syn_workqueue.c \
	src/syntropic/log/syn_log.c src/syntropic/log/syn_datalog.c src/syntropic/cli/syn_cli.c \
	src/syntropic/input/syn_button.c src/syntropic/input/syn_encoder.c \
	src/syntropic/output/syn_led.c src/syntropic/output/syn_soft_pwm.c \
	src/syntropic/dsp/syn_filter.c src/syntropic/dsp/syn_signal.c \
	src/syntropic/control/syn_pid.c \
	src/syntropic/motor/syn_stepper.c src/syntropic/motor/syn_servo.c \
	src/syntropic/motor/syn_dc_motor.c src/syntropic/motor/syn_motor_ctrl.c \
	src/syntropic/motor/syn_actuator.c \
	src/syntropic/proto/syn_cobs.c src/syntropic/proto/syn_modbus.c \
	src/syntropic/sensor/syn_sensor.c src/syntropic/storage/syn_param.c \
	src/syntropic/debug/syn_trace.c src/syntropic/debug/syn_profiler.c \
	src/syntropic/system/syn_boot.c src/syntropic/system/syn_errlog.c \
	src/syntropic/system/syn_power.c src/syntropic/system/syn_hwwdt.c \
	src/syntropic/system/syn_fwupdate.c src/syntropic/system/syn_fwboot.c \
	src/syntropic/display/syn_canvas.c src/syntropic/ui/syn_menu.c \
	src/syntropic/ui/syn_imgui.c \
	src/syntropic/net/syn_router.c src/syntropic/net/syn_heartbeat.c \
	src/syntropic/net/syn_http.c src/syntropic/net/syn_httpd.c \
	src/syntropic/net/syn_transport_tcp.c \
	src/syntropic/net/syn_websocket.c \
	src/syntropic/net/syn_dns.c \
	src/syntropic/net/syn_mqtt.c \
	src/syntropic/util/syn_json_write.c src/syntropic/util/syn_json_read.c \
	src/syntropic/sched/syn_ao.c \
	src/syntropic/storage/syn_vfs.c \
	src/syntropic/storage/syn_lfs.c \
	src/syntropic/net/syn_coap.c \
	src/syntropic/dsp/syn_biquad.c \
	src/syntropic/dsp/syn_fft.c \
	src/syntropic/system/syn_fault.c

# Unity framework
UNITY_SRCS := tests/unity/unity.c

# Mock port layer
MOCK_SRCS := tests/mocks/mock_port.c

# All per-module test files (everything except old monolith and .inc)
TEST_SRCS := $(filter-out tests/test_multitask.c tests/test_new_modules.inc.c, \
	$(wildcard tests/test_*.c))

ALL_SRCS := $(SYN_SRCS) $(UNITY_SRCS) $(MOCK_SRCS) $(TEST_SRCS)
TARGET   := test_unity

.PHONY: test clean

test: $(TARGET)
	./$(TARGET)

$(TARGET): $(ALL_SRCS)
	$(CC) $(CFLAGS) $^ -o $@ -lm

clean:
	rm -f $(TARGET)
