[platformio]
src_dir = ../../

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
build_flags =
  -include syn_config.h
  -Iexamples/stm32_serial/include
  -I../../
build_src_filter =
  -<*>
  +<examples/stm32_serial/src/main.c>
  +<syntropic/drivers/syn_gpio.c>
  +<syntropic/drivers/syn_uart.c>
  +<syntropic/util/syn_ringbuf.c>
  +<syntropic/sched/syn_sched.c>
  +<syntropic/sched/syn_timer.c>
  +<syntropic/log/syn_log.c>
  +<syntropic/cli/syn_cli.c>
  +<syntropic/util/syn_fmt.c>
  +<syntropic/output/syn_led.c>
  +<syntropic/util/syn_fsm.c>
  +<port/stm32_hal/port_stm32_hal.c>
monitor_speed = 115200
